srping:
  application:
    name: config-client-namber
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
     default-zone: localhost:8761/eureka
  instance:
    prefer-ip-address: true
    env: dev
